spring:
#  profiles:
#    active: prod
  messages:
    basename: i18n/messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: bwsilent7@gmail.com
    password: 'uxum tumj trfn geuz'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/myafiback?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: myafiback
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

application:
  security:
    jwt:
      secret-key: MmFmYzk2M2E1MmNlYzc4OGUzMjdkZDY3NzA0NDZmODIwZDdiY2Y1YTYwMWE5MWU4YWVjMDA5Zjc3YTcwZTM0M2Q1NDk2ZWRjNmFlOThhMDU1ZjBiOWRhOGFkOGExMzU5ZjEyMTkwMDA2M2Q5ZjIwNjUwYjBkOTYyYzA4M2NkOTM
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
